env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
   # disable rules from base configurations
   no-console: off
   import/extensions: off # FIXME: remove when rule will be adjusted for new nodejs version
